[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
dutch_auction = "ATr4QpNHBjnT14tUEei26zsyMo6AyN9yaAoeLhg3ue26"

[programs.devnet]
dutch_auction = "ATr4QpNHBjnT14tUEei26zsyMo6AyN9yaAoeLhg3ue26"

[programs.mainnet]
dutch_auction = "ATr4QpNHBjnT14tUEei26zsyMo6AyN9yaAoeLhg3ue26"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
