[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
dutch_auction = "dtchBqYrywpfV6uKkrrRo8fW56Lg6cfAKMEgTt8sUXx"

[programs.mainnet]
dutch_auction = "dtchBqYrywpfV6uKkrrRo8fW56Lg6cfAKMEgTt8sUXx"

[scripts]
test = "MY_WALLET=$HOME/.config/solana/id.json ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
