[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
dutch_auction = "F93nCR6gwq168KHLPNuY8VSK4eW6Dh9rwUe8Mkf8zPGY"

[programs.devnet]
dutch_auction = "F93nCR6gwq168KHLPNuY8VSK4eW6Dh9rwUe8Mkf8zPGY"

[programs.mainnet]
dutch_auction = "F93nCR6gwq168KHLPNuY8VSK4eW6Dh9rwUe8Mkf8zPGY"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
